/**
 * Code review and all AI responses are generated by the Gemini API.
 * Clerk is used elsewhere only for user authentication.
 */
const { GoogleGenerativeAI } = require('@google/generative-ai');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

/**
 * Generate AI response using Gemini 1.5 Flash (used for code review and chat)
 * @param {string} prompt - User message / prompt
 * @returns {Promise<string>} AI response text
 */
async function generateAIResponse(prompt) {
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
  const result = await model.generateContent(prompt);
  const response = result.response;
  return response.text();
}

module.exports = { generateAIResponse };
